GET http://localhost:3003/api/blogs

### 

POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "This is title",
    "author": "This is author",
    "url": "This is URL",
    "likes": 100
}