GET http://localhost:3003/api/blogs

### 

POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "This is title4",
    "author": "This is author4",
    "url": "This is URL4",
    "likes": 400
}

###

DELETE http://localhost:3003/api/blogs/64f823308eb0e59692836c07

### 

PUT http://localhost:3003/api/blogs/64f76999c5f02d2ebbf73d66
content-type : application/json

{
    "title": "This is title2",
    "author": "This is author2",
    "url": "This is URL2",
    "likes": 500
}

### 
POST http://localhost:3003/api/user
content-type: application/json

{
    "username":"port2",
    "name":"port2",
    "password":"port2"
}


###
GET http://localhost:3003/api/user